# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-23 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='columns',
            field=models.CharField(choices=[('6', 'Two columns'), ('4', 'Three columns'), ('3', 'Four Columns')], default='3', max_length=1),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='description_heading',
            field=models.CharField(default='Project description', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='details_heading',
            field=models.CharField(default='Project details', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='featured_video',
            field=models.TextField(blank=True, help_text='Optional, putting video embed code (iframe) here, will override a Featured image specified above.  This has been tested to work with Youtube and Vimeo, but may work with other iframes as well.'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='layout',
            field=models.PositiveIntegerField(choices=[(1, 'Slideshow/video above, content below'), (2, 'Slideshow/video on left, content on right'), (3, 'Slideshow/video on right, content on left')], default=1),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='website',
            field=models.CharField(blank=True, help_text='A link to the finished project or clients website  (optional)', max_length=2000),
        ),
    ]
