# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-15 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20171223_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='related_items',
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='website',
            field=models.CharField(blank=True, help_text='A link to the finished project or clients website (optional)', max_length=2000),
        ),
    ]
